sudo: required

services: docker

before_install:
  - docker-compose up --build -d
  #add this on lecture100 本番環境にデプロイするためにloginする。loginするときはusenameなどを聞かれるが、今回はインタラクティブなやりとりはできないので、-u -pをつける
  - docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" registry.heroku.com

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test


  #add this on lecture100
deploy:
  provider: script
  script:
    docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f Dockerfile.prod .;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    #herokuのコマンド。loginしないとだが、before_installのところに"$HEROKU_API_KEY"の環境変数が設定されている場合は、それを見て自動loginしてくれる
    heroku run --app $HEROKU_APP_NAME rails db:migrate;
    
  #このdeployはmasterにmargeされた時だけ実行させたい。ので以下。
  on:
    branch: master
